[pytest]
markers =
    positive: Marker for positive tests
    negative: Marker for nigative tests
    smoke: Marker for smoke tests
    requires_captcha: Needed manual passage

addopts = -v -s --alluredir=allure-results
testpaths = tests
pythonpath = .